# NOTE: For maximum performance, build using a nightly compiler
# If you are using rust stable, remove the "-Z share-generics=y" below.

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Z", "share-generics=y"]

# NOTE: you must install [Mach-O LLD Port](https://lld.llvm.org/MachO/index.html) on mac. you can easily do this by installing llvm which includes lld with the "brew" package manager:
# `brew install llvm`
[target.x86_64-apple-darwin]
rustflags = [
  "-C",
  "link-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",
  "-Z",
  "share-generics=y",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C",
  "link-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld",
  "-Z",
  "share-generics=y",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Z", "share-generics=n"]
